name: CI
on: [push]

jobs:
  build:
    name: Test Apollo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install and start jbrowse
        uses: actions/setup-node@v3
      - run: |
          cd ../
          git clone https://github.com/GMOD/jbrowse-components
          cd jbrowse-components
          pwd
          yarn install
          yarn --cwd products/jbrowse-web start &

      - name: Start container
        run: docker compose -f docker-compose.yml up -d

      - name: Install Apollo
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: |
          pwd
          yarn install
          yarn --cwd packages/apollo-shared start &
          yarn --cwd packages/apollo-collaboration-server run cypress:start &
          yarn --cwd packages/jbrowse-plugin-apollo start
