name: CI
on: [push]

jobs:
  build:
    name: Test Apollo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install jbrowse
        uses: actions/checkout@v3
        with:
          repository: GMOD/jbrowse-components
          path: jbrowse
          ref: main
      - run: |
          cd jbrowse \
          yarn install \
          yarn products/jbrowse-web start 

      - name: Install Apollo
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: yarn install


