name: CI
on: [push]

jobs:
  build:
    name: Test Apollo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Download jbrowse
        uses: actions/checkout@v3
        with:
            repository: GMOD/jbrowse-components
            path: jbrowse-components
      
      - name: Download apollo
        uses: actions/checkout@v3
        with:
            path: Apollo3

      - name: Install and start jbrowse 
        run: |
          cd jbrowse-components
          pwd; ls
          yarn install
          yarn --cwd products/jbrowse-web start &
          for i in {1..6}
          do
            echo "Waiting for jbrowse to start"
            sleep 10
            set +e
            nc -z localhost 3000
            exit_code=$?
            set -e {0}
            if [ "$exit_code" -eq 0 ]
            then
              echo "Jbrowse started"
              exit 0
            fi
          done
          echo "Failed to start jbrowse"
          exit 1

      - name: Start container
        run: docker compose -f docker-compose.yml up -d

      - name: Install and start Apollo
        run: |
          cd Apollo3
          pwd; ls
          yarn install
          yarn --cwd packages/apollo-shared start &
          yarn --cwd packages/apollo-collaboration-server run cypress:start &
          yarn --cwd packages/jbrowse-plugin-apollo start
