name: CI
on: [push]

jobs:
  build:
    name: Test Apollo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install
        run: yarn --immutable

      - name: Get latest JBrowse
        working-directory: packages/jbrowse-plugin-apollo
        run: yarn run jbrowse create --nightly .jbrowse

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: 7
          mongodb-replica-set: test-rs

      - name: Test plugin
        working-directory: packages/jbrowse-plugin-apollo
        run: yarn run test:e2e
