name: CI
on: [push]

jobs:
  build:
    name: Test Apollo
    runs-on: ubuntu-latest
    steps:
      - run: |
          cd ../
          git clone https://github.com/GMOD/jbrowse-components
          cd jbrowse-components
          yarn install
          yarn --cwd products/jbrowse-web start 

      - uses: actions/checkout@v3

      - name: Install Apollo
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: |
          pwd
          yarn install


