name: CI
on: [push]

jobs:
  build:
    name: Test Apollo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install and start jbrowse
        uses: actions/checkout@v3
        with:
            repository: GMOD/jbrowse-components
            path: jbrowse
      - run: |
          #cd ../
          #git clone https://github.com/GMOD/jbrowse-components
          #cd jbrowse-components
          pwd; ls
          yarn install
          yarn --cwd products/jbrowse-web start &

          #- name: Start container
          #run: docker compose -f docker-compose.yml up -d

      - name: Install Apollo
        uses: actions/checkout@v3
        with:
            path: apollo
      - run: |
          ls ../
          pwd; ls
          yarn install
          yarn --cwd packages/apollo-shared start &
          yarn --cwd packages/apollo-collaboration-server run cypress:start &
          yarn --cwd packages/jbrowse-plugin-apollo start
