name: CI
on: [push]

jobs:
  build:
    name: Test Apollo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Apollo
        uses: actions/setup-node@v3
        uses: actions/checkout@v3
        with:
          node-version: 18.x
      - run: yarn install
